### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Grady-1028** [TheRyanMajd/img-to-ics#1]
Hey Ryan it's Grady, saw your post on LinkedIn and decided to check out the project, looks pretty cool and I've been impressed by GPT4o. I'm at work so I didn't have a lot of time but I ran into a couple errors on my first attempts. Could be user error since I didn't poke around much but here are the errors, (not sure why it would output the prompt lol):

**GUI:**
Input:
PS C:\Users\gport3\Documents\img-to-ics-main> python imgToICS_GUI.py

Output :
Review the image. Take in all information related to the event and Output ONLY the raw text of a .ICS file about the calendar event. Make sure to include Created-By-Ryan-Majd in the PRODID. Also, assume the current year is 2024.
Traceback (most recent call last):
  File "C:\Users\gport3\Documents\img-to-ics-main\imgToICS_GUI.py", line 98, in <module>
    output_ics = generate_ics_file(values[0], values[1], values[2])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gport3\Documents\img-to-ics-main\imgToICS_GUI.py", line 54, in generate_ics_file
    ics_content = response.json()['choices'][0]['message']['content']
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'choices'

**CLI:**
Input:
PS C:\Users\gport3\Documents\img-to-ics-main> python imgToICS_CLI.py 'C:\Users\gport3\Documents\img-to-ics-main\images\example_event.jpeg' 'C:\Users\gport3\Documents\img-to-ics-main\Output\'

Output:
Traceback (most recent call last):
  File "C:\Users\gport3\Documents\img-to-ics-main\imgToICS_CLI.py", line 5, in <module>
    from openai import OpenAI
ModuleNotFoundError: No module named 'openai'

**Comment by TheRyanMajd** [comment]
Hey Grady,

Thanks for checking out my project and for your feedback! I appreciate you taking the time to try it out and report these issues. It looks like the errors you're encountering are due to a couple of reasons:

1. The package openai is required to run the program, run this command in the terminal:

```
pip install openai
``` 

2. Make sure you have an OpenAI [API Key](https://platform.openai.com/api-keys), I will post a revised version after work today which will make errors more obvious since the output is confusing!

**Comment by TheRyanMajd** [comment]
I went ahead and pushed the updated code, pull and try it out!
