### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by Grady-1028** [TheRyanMajd/img-to-ics#2]
Trying again with the updated repo, just the CLI version this time for convenience. I kept getting an API error so I added an extra block of error handling for HTTP codes, and this is what it looked like using the example image included in the repo:

Input:
PS C:\Users\gport3\Documents\img-to-ics-main> python imgToICS_CLI.py 'C:\Users\gport3\Documents\img-to-ics-main\images\example_event.jpeg' 'C:\Users\gport3\Documents\img-to-ics-main\Output\'

Output:
Failed to get a valid response from the API: 429 {
    "error": {
        "message": "Request too large for gpt-4o in organization org-0YdEvg3ibD2BAWzXfNUQVN8X on tokens per min (TPM): Limit 30000, Requested 155077. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.",
        "type": "tokens",
        "param": null,
        "code": "rate_limit_exceeded"
    }
}

So I guess it's trying to use 155077 token on the one input lol, not sure how it's bypassing the "max_tokens": 300, or why it would ever be that large anyways

One more thing is that I had to hard code the 'KEY' variable into the script because for some reason it just wasn't finding it in the .env file I made in the directory, even though I double checked to make sure the format was correct. Looking forward to hearing your thoughts on this, I've never interacted with APIs outside of a lab environment before so this is fun and good practice :)

**Comment by TheRyanMajd** [comment]
I advise against hard-coding the 'KEY' variable. Since the max_tokens is set to 300 it must be an issue with the output as I do not see how it would be an input issue. I updated the repo a little more and added an install script, I would make sure that all packages are installed correctly, and the HTTP request error handling might have looped the request multiple times. Tokens are calculated per minute so this may be the case. 

this is my .env file (make sure to call it .env and do not include any name in front of it i.e. apikey.env)
```
OPENAI_API_KEY = 'sk-proj-*************'
```

**Comment by Grady-1028** [comment]
just got back from vacation and tried again with the updated repo, worked like a charm :) cool stuff
